### ISSUE TITLE
markdown cell formats on mouse-down but unformats on mouseup

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1336]
if you click in a markdown cell but out of the editable part of it, then the text is momentarily formatted and then unformatted.

**Comment by buob** [comment]
I suspect this actually caused the regression mentioned in https://github.com/twosigma/beaker-notebook/issues/1363

**Comment by scottdraves** [comment]
this was fixed by the codemirror change.

**Comment by buob** [comment]
This still happen when you click on the markdown cell instead of the contents

**Comment by scottdraves** [comment]
yup this is happening again but in reverse, if the cell is in edit mode and you click in the area between the cell box and the codemirror, then the markdown is formatted on mousedown and unformatted on mouseup.

in this case, it should not format and just move the cursor to the beginning or end, as if it were a code cell.
