### ISSUE TITLE
can't click on last line of code cell

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1493]
a user (ben) reported that the last line of text in a code cell can't be clicked on.
it happens when there is a wide line, and the scroll bar appears but it overlaps with the last line.
it should be below all the text.  also i think it should be always visible, not vanishing when still.
i was initially unable to reproduce this, but then it came back with a vengeance and now it happens to me all the time.

**Comment by samccone** [comment]
This is windows specific correct?

**Comment by scottdraves** [comment]
i am not seeing it on mac.  on windows i actually see something much worse now:

![windows-scrollbars](https://cloud.githubusercontent.com/assets/963093/7684502/853de074-fd54-11e4-8e42-eac9ed2f8a10.png)

it's like a double scrollbar, sticking down into the output area.
plus you can see the little vertical scrollbar on the output side that i mentioned this morning.
note this is a 4k display, and i have dpi scaling set at 150%.

**Comment by samccone** [comment]
kk, looking into it

**Comment by samccone** [comment]
Here is a notebook at 150% zoom on chrome 40.x

![screen shot 2015-05-19 at 11 08 08 am](https://cloud.githubusercontent.com/assets/883126/7706259/60d369b6-fe17-11e4-9dda-814a3642b1e9.png)

I am getting a single scrollbar at the bottom like you. I can still click on the last line unlike you.
Can you still reproduce this?

**Comment by scottdraves** [comment]
the scaling that i am talking about is in the windows display settings, not the browser.
since that is a 4k issue let's just forget about that.

but, still on windows with no scaling on any display with chrome 40, there are two problems:

the horizontal scrollbar is in the wrong place, it's too far down, overlapping the run button in normal mode, or the output area in advanced mode.

and the little vertical scrollbar shows up too, which is bad.  create a JS cell and evaluate "10" and it appears.  it does not appear for HTML cells, but does for JS and Python.

**Comment by scottdraves** [comment]
this pic might be clearer, two cells one showing each bug.
![windows-scrollbars3](https://cloud.githubusercontent.com/assets/963093/7709498/7939be88-fe2b-11e4-9518-d7f132a5c8c9.png)

**Comment by samccone** [comment]
thanks for the detailed explanation on it :white_check_mark:

**Comment by scottdraves** [comment]
Here's a similar problem on Mac, it's just less visible with one line output.  The scrollbar is barely visible immediately right of the output hamburger:
![screen shot 2015-05-19 at 2 26 45 pm](https://cloud.githubusercontent.com/assets/963093/7710645/3efea168-fe33-11e4-903b-fbe18604583d.png)
with two lines of output it's clearer:
![screen shot 2015-05-19 at 2 24 03 pm](https://cloud.githubusercontent.com/assets/963093/7710660/56374510-fe33-11e4-943c-245295f2559e.png)

**Comment by samccone** [comment]
Fix incoming for the right scroll bar! 

Still working on reproducing the horizontal scrollbar case

**Comment by scottdraves** [comment]
right output scroll bar fixed: https://github.com/twosigma/beaker-notebook/pull/1638

**Comment by samccone** [comment]
is this all resolved now @scottdraves ?

**Comment by scottdraves** [comment]
no we still have the horizontal one but i am still trying to come up with better repro for you.

**Comment by samccone** [comment]
kk :+1:

**Comment by scottdraves** [comment]
:dolphin:

**Comment by samccone** [comment]
:hand:

**Comment by scottdraves** [comment]
bug fixed since last internal release.
