### ISSUE TITLE
file not found error not reported when building mime container

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5078]
if you call SVG("file-does-no-exist") then you just get
> [Fatal Error] :1:1: Content is not allowed in prolog.
but the error should be "file not found".
ditto for Image().

**Comment by scottdraves** [comment]
the errors are still not reported correctly.
need https://github.com/twosigma/beakerx/issues/5095
should not be catching the exn at all in the runtime,
the kernel should catch and report.

**Comment by fishera123** [comment]
fixed in #5095

**Comment by scottdraves** [comment]
i am still seeing these errors reported to stderr, not as error outputs.
