### ISSUE TITLE
beacker-jupyterlab extension conflict with plotly-extension

### ISSUE THREAD

**Issue by asaglimbeni** [twosigma/beakerx#7703]
Hi, 
I have some trouble to enalbe the beacker-jupyterlab extension , because when it is enabled at the same time with the plotly-extension, the python notebooks start to have problem infact from the existing notebook the cells with plotly graph as output disapear both output and code. 
here the list of the extension installed : 
JupyterLab v0.32.1
Known labextensions:
   app dir: /home/zeppelin/anaconda2/envs/py3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.35.0  enabled  OK
        @jupyterlab/hub-extension v0.9.0  enabled  OK
        @jupyterlab/plotly-extension v0.16.0 disabled OK
        @mflevine/jupyterlab_html v0.1.4  enabled  OK
        beakerx-jupyterlab v1.0.0  enabled  OK
        jupyterlab-toc v0.2.1  enabled  OK

After I disabled beakerx-jupyterlab extension the cells with plotly graph return to work fine. 
I guess there are some problems loading static js library: In Chrome console I have the follow errors: 
- Plugin 'beakerx' failed to activate. index.js:267
- Error: "No provider for: jupyter.extensions.jupyterWidgetRegistry."
- ReferenceError: "Plotly is not defined"

Last detail , If I use a notebook with scala providede by beakerx it works fine.
If you need other informations let me know .

**Comment by piorek** [comment]
Tested it against newer versions of extension and lab looks like it's fixed now
```
JupyterLab v0.35.4
Known labextensions:
   app dir: /home/lukasz/miniconda3/envs/labx/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
        @jupyterlab/plotly-extension v0.18.1  enabled  OK
        beakerx-jupyterlab v1.3.0  enabled  OK*

   local extensions:
        beakerx-jupyterlab: /home/lukasz/code/codete/beakerx/js/lab

```
```
plotly                    3.5.0                      py_0    conda-forge
```
![image](https://user-images.githubusercontent.com/743617/51034798-2c187480-15a8-11e9-8926-bb868a1ec01e.png)
![image](https://user-images.githubusercontent.com/743617/51034825-44888f00-15a8-11e9-9d78-0af2d652a6f8.png)

**Comment by dclong** [comment]
Yet a similar issue still exists with HoloViews.

https://github.com/twosigma/beakerx/issues/7690
